name: Deploy React Application (GitHub Pages)

# Only fire this workflow on pushes to the main branch.
# Allows for Pull-Requests to be reviewed and tested before deployment.
on:
  push:
    branches: [ main ]

# The Jobs to Run.
jobs:
  build_test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        # Use the LTS Release of Node. (https://nodejs.org/en/)
        node-version: [14.x] 

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so this job can access it.
      - uses: actions/checkout@v2
      - name: SetUp Node.js v${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          # Use LTS node version as defined from above.
          node-version: ${{ matrix.node-version }} 
          
        # Attempt to Build the artifact. (catches any compilation errors in our application)  
      - name: npm ci, build 
        run: |
          npm ci
          npm run build --if-present
      - name: Deploy To gh-pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          # Our Deploy Key for gh-pages.
          deploy_key: ${{ secrets.ACTIONS_DEPLOY_KEY }} 
          
          # Use React's default build directory. 
          publish_dir: ./build 
